export const FILTER_ALL = "FILTER_ALL";
export const FILTER_ACTIVE = "FILTER_ACTIVE";
export const FILTER_COMPLETED = "FILTER_COMPLETED";
export const FILTER_PINNED = "FILTER_PINNED";
export const FILTER_IMPORTANT = "FILTER_IMPORTANT";
